# docker-compose up will create a network that is named after the current directory
# create a container by its setting under the services scope
# eg. 

version: "3"
services:

  ubuntu : # image name
    container_name: ubuntu_test
    build: ./ubuntu/
    platform: linux/amd64 # for Mac Silicon
    tty: true
    ports:
      - "8001:8001"
    volumes:
      # volumes will synchronise local directory with the container 
      # <local_directory>:<container_directory>
      - /Users/gaozheng/Documents/coding/practise_python/postgresql_practise:/root/code
    
  db: # image name
    container_name: db_test
    platform: linux/amd64 # for Mac Silicon
    build: ./database/
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: secret

networks:
  postgresql_practise: # docker network name
    driver: bridge